# Evore Bot Configuration

[[bots]]
name = "EV-Bot-1"
auth_id = 1
strategy = "ev"
slots_left = 1
bankroll = 220_000_000
signer_path = "/Users/kriptikz/Development/game-wallets/game-wallet-1.json"
manager_path = "/Users/kriptikz/Development/game-wallets/manager-1.json"

[bots.strategy_params]
type = "ev"
max_per_square = 10_000_000
min_bet = 1_000_000
ore_value = 500_000_000
