# Evore Bot Configuration
# priority_fee: micro-lamports per CU (5000 = ~0.000007 SOL @ 1.4M CU)
# jito_tip: lamports for Jito tip (200_000 = 0.0002 SOL, required for Helius Sender)

[[bots]]
name = "EV ORE"
auth_id = 1
strategy = "ev"
slots_left = 1
bankroll = 150_000_000
attempts = 3
priority_fee = 6_000
jito_tip = 400_000
signer_path = "/Users/kriptikz/Development/game-wallets/game-wallet-1.json"
manager_path = "/Users/kriptikz/Development/game-wallets/manager-1.json"

[bots.strategy_params]
type = "ev"
max_per_square = 50_000_000
min_bet = 10_000
ore_value = 700_000_000

[[bots]]
name = "10%"
auth_id = 1
strategy = "percentage"
slots_left = 15
bankroll = 1_500_000_000
attempts = 1
priority_fee = 4_000
jito_tip = 200_000
signer_path = "/Users/kriptikz/Development/game-wallets/perc-bot-2.json"
manager_path = "/Users/kriptikz/Development/game-wallets/perc-bot-2-manager.json"

[bots.strategy_params]
type = "percentage"
percentage = 5000
squares_count = 25

[[bots]]
name = "EV Pure SOL"
auth_id = 1
strategy = "ev"
slots_left = 3
bankroll = 150_000_000
attempts = 2
priority_fee = 6_000
jito_tip = 200_000
signer_path = "/Users/kriptikz/Development/game-wallets/pure-sol-ev-bot.json"
manager_path = "/Users/kriptikz/Development/game-wallets/pure-sol-ev-manager.json"

[bots.strategy_params]
type = "ev"
max_per_square = 50_000_000
min_bet = 10_000
ore_value = 0
